import Head from 'next/head'
import Layout from '@/components/Layout'
import MovieList from '@/components/MovieList/MovieList'
import { movieService } from '@/services/movie-service'
import { IErrorResponse, IMovieItem } from '@/types/moviesTypes'
import Search from '@/components/Search/Search'
import { GetServerSideProps } from 'next/types'


export default function Home({
  moviesResponse
} : {
  moviesResponse: IMovieItem[] | IErrorResponse, 
}) {

  return (
    <>
    <Head>
        <title>Movies Search</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
    </Head>
    <Layout>
      <Search />
      <MovieList moviesResponse={moviesResponse} />
    </Layout>
    </>
  )
}


export const getServerSideProps = (async ({query}) => {
  const search = Array.isArray(query.search) ? query.search[0] : String(query.search)
  const movieType = Array.isArray(query.type) ? query.type[0] : query.type
  const year = Array.isArray(query.year) ? query.year[0] : String(query.year)

  // console.log('query', query);
  
  const moviesResponse = await movieService.getAll(
    {
      search, 
      type: movieType || '', 
      year
    })
  
  return { props: { moviesResponse: moviesResponse} }

}) satisfies GetServerSideProps<{
  moviesResponse: IMovieItem[] | IErrorResponse,
}>